// <auto-generated />
namespace ServiceHub.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class rowVerisonsaltered : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rowVerisonsaltered));
        
        string IMigrationMetadata.Id
        {
            get { return "201304250913119_rowVerisons-altered"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
