// <auto-generated />
namespace ServiceHub.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class rowversionfixed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rowversionfixed));
        
        string IMigrationMetadata.Id
        {
            get { return "201304171713538_rowversion-fixed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
